spring:
  # Application Config
  application:
    name: pgp-userCenter
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pgp
    username: root
    password: 110680100029wbn
  # Mail Config
  mail:
    host: smtp.163.com
    port: 25
    username: wangbaonandlut@163.com
    password: NYVJSZHWLOQIYFYT
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

# Mybatis Plus Config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值

# Redis Config
redis:
  host: localhost
  port: 6379
