spring:
  # Application Config
  application:
    name: pgp-userCenter
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pgp
    username: root
    password: *********
  # Mail Config
  mail:
    host: smtp.163.com
    port: 25
    username: *********
    password: *********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8080

# Mybatis Plus Config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名
      logic-delete-field: isDelete
      # 逻辑删除的值（默认为 1）
      logic-delete-value: 1
      # 逻辑未删除的值（默认为 0）
      logic-not-delete-value: 0

my-app:
  upload:
    # 上传路径
    uploadPath: G:\PGP_Dev\PGP_ProjectPath\userDataPath
    # 分片大小
    uploadChunkSize: #{5 * 1024 * 1024}


# Redis Config
redis:
  host: localhost
  port: 6379
